service: s3-to-frameio-lambda-copy
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  memorySize: 512
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
      Resource: "arn:aws:s3:::*"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  copy:
    handler: handler.copy
    reservedConcurrency: 1
    events:
      - http:
          path: /copy
          method: post
