service: s3-to-frameio-lambda-copy
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  memorySize: 1024
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
      Resource: "arn:aws:s3:::*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "arn:aws:lambda:us-east-1:*"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  main:
    handler: handler.main
    reservedConcurrency: 1
    events:
      - http:
          path: /
          method: post
  copy:
    handler: handler.copy
    reservedConcurrency: 5
